name: baidunetdisk

on:
  push:
    paths:
    - 'baidunetdisk/Dockerfile'
    - 'baidunetdisk/root/**'
  workflow_dispatch:

jobs:
  job1:
    name: buildx tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: 'Set env'
        run: |
          echo "BAIDUNETDISK_VER=$(echo `grep -n "BAIDUNETDISK_VER=" baidunetdisk/Dockerfile`|awk -F= '{print $2}')" >> $GITHUB_ENV
          echo "BAIDUNETDISK_VER_ARM64=$(echo `grep -n "BAIDUNETDISK_VER_ARM64=" baidunetdisk/Dockerfile`|awk -F= '{print $2}')" >> $GITHUB_ENV
          echo "BASEIMAGE_GUI_VER=$(echo `grep -n "baseimage-gui" baidunetdisk/Dockerfile`|awk -Fv '{print $2}')" >> $GITHUB_ENV

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: latest

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./baidunetdisk
          file:  ./baidunetdisk/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            johngong/baidunetdisk:v_${{ env.BAIDUNETDISK_VER }}_${{ env.BASEIMAGE_GUI_VER }}_amd64
            ghcr.io/gshang2017/baidunetdisk:v_${{ env.BAIDUNETDISK_VER }}_${{ env.BASEIMAGE_GUI_VER }}_amd64

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./baidunetdisk
          file:  ./baidunetdisk/Dockerfile
          platforms: linux/arm64
          push: true
          tags: |
            johngong/baidunetdisk:v_${{ env.BAIDUNETDISK_VER_ARM64 }}_${{ env.BASEIMAGE_GUI_VER }}_arm64v8
            ghcr.io/gshang2017/baidunetdisk:v_${{ env.BAIDUNETDISK_VER_ARM64 }}_${{ env.BASEIMAGE_GUI_VER }}_arm64v8

      - name: create version tag
        run: |
          docker buildx imagetools create -t johngong/baidunetdisk:latest \
            johngong/baidunetdisk:v_${{ env.BAIDUNETDISK_VER }}_${{ env.BASEIMAGE_GUI_VER }}_amd64 \
            johngong/baidunetdisk:v_${{ env.BAIDUNETDISK_VER_ARM64 }}_${{ env.BASEIMAGE_GUI_VER }}_arm64v8

      - name: create version tag(ghcr.io)
        run: |
          docker buildx imagetools create -t ghcr.io/gshang2017/baidunetdisk:latest \
            ghcr.io/gshang2017/baidunetdisk:v_${{ env.BAIDUNETDISK_VER }}_${{ env.BASEIMAGE_GUI_VER }}_amd64 \
            ghcr.io/gshang2017/baidunetdisk:v_${{ env.BAIDUNETDISK_VER_ARM64 }}_${{ env.BASEIMAGE_GUI_VER }}_arm64v8

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: johngong/baidunetdisk
          short-description: 官方百度网盘客户端VNC版:(baidunetdisk:${{ env.BAIDUNETDISK_VER }})
          readme-filepath: ./baidunetdisk/README.md
