name: libtorrent

on:
  push:
    paths:
    - 'qBittorrent/Dockerfile.libtorrent'
    - 'qBittorrent/Dockerfile.libtorrent2'
  workflow_dispatch:

jobs:
  job1:
    name: buildx tag
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: 'Set env'
        run: |
          echo "LIBTORRENT_VER=$(echo `grep -n "LIBTORRENT_VER=" qBittorrent/Dockerfile.libtorrent`|awk -F= '{print $2}')" >> $GITHUB_ENV
          echo "LIBTORRENT_ALPINE_VER=$(echo `grep -n "alpine" qBittorrent/Dockerfile.libtorrent`|awk -F: '{print $3}')" >> $GITHUB_ENV
          echo "LIBTORRENT2_VER=$(echo `grep -n "LIBTORRENT_VER=" qBittorrent/Dockerfile.libtorrent2`|awk -F= '{print $2}')" >> $GITHUB_ENV
          echo "LIBTORRENT2_ALPINE_VER=$(echo `grep -n "alpine" qBittorrent/Dockerfile.libtorrent2`|awk -F: '{print $3}')" >> $GITHUB_ENV

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: latest

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Check image exist
        id: libtorrent-check-step
        run: |
          if [ `DOCKER_CLI_EXPERIMENTAL=enabled docker manifest inspect ghcr.io/gshang2017/libtorrent:${{ env.LIBTORRENT_VER }}-alpine-${{ env.LIBTORRENT_ALPINE_VER }} > /dev/null  2>&1; echo $?` == "0" ];then echo "skipnext=true" >> $GITHUB_OUTPUT;fi

      - name: Build and push
        if : ( steps.libtorrent-check-step.outputs.skipnext  != 'true' )
        uses: docker/build-push-action@v6
        with:
          context: ./qBittorrent
          file: ./qBittorrent/Dockerfile.libtorrent
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: |
            ghcr.io/gshang2017/libtorrent:latest
            ghcr.io/gshang2017/libtorrent:1
            ghcr.io/gshang2017/libtorrent:${{ env.LIBTORRENT_VER }}-alpine-${{ env.LIBTORRENT_ALPINE_VER }}

      - name: Check image exist
        id: libtorrent2-check-step
        run: |
          if [ `DOCKER_CLI_EXPERIMENTAL=enabled docker manifest inspect ghcr.io/gshang2017/libtorrent:${{ env.LIBTORRENT2_VER }}-alpine-${{ env.LIBTORRENT2_ALPINE_VER }} > /dev/null  2>&1; echo $?` == "0" ];then echo "skipnext=true" >> $GITHUB_OUTPUT;fi

      - name: Build and push
        if : ( steps.libtorrent2-check-step.outputs.skipnext  != 'true' )
        uses: docker/build-push-action@v6
        with:
          context: ./qBittorrent
          file: ./qBittorrent/Dockerfile.libtorrent2
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: |
            ghcr.io/gshang2017/libtorrent:2
            ghcr.io/gshang2017/libtorrent:${{ env.LIBTORRENT2_VER }}-alpine-${{ env.LIBTORRENT2_ALPINE_VER }}
